### ISSUE TITLE
Troubleshoot TravisCI build randomly failing (local build works)

### ISSUE THREAD

**Issue by aschrijver** [engagingspaces/vertx-graphql-service-discovery#5]
TravisCI build fails with NPE in `tearDown()` of tests:
```
io.engagingspaces.graphql.servicediscovery.publisher.SchemaPublisherTest > should_Publish_Schema_Definition FAILED

    java.lang.NullPointerException
        at io.engagingspaces.graphql.servicediscovery.publisher.SchemaRegistrar.lambda$handleCloseCompletion$13(SchemaRegistrar.java:201)
        at io.engagingspaces.graphql.servicediscovery.publisher.SchemaRegistrar$$Lambda$78/2097777478.handle(Unknown Source)
        at io.vertx.core.impl.CompositeFutureImpl.setHandler(CompositeFutureImpl.java:152)
        at io.engagingspaces.graphql.servicediscovery.publisher.SchemaRegistrar.handleCloseCompletion(SchemaRegistrar.java:199)
        at io.engagingspaces.graphql.servicediscovery.publisher.SchemaRegistrar.close(SchemaRegistrar.java:172)
        at io.engagingspaces.graphql.servicediscovery.publisher.SchemaPublisher.close(SchemaPublisher.java:175)
        at io.engagingspaces.graphql.servicediscovery.publisher.SchemaPublisherTest.tearDown(SchemaPublisherTest.java:59)
```

**Comment by aschrijver** [comment]
Had to upgrade to latest Gradle 3.5 version (from 2.14) for Travis wrapper to fix the issue.

**Comment by aschrijver** [comment]
Successful build was short-lived. After commit https://github.com/engagingspaces/vertx-graphql-service-discovery/commit/2f1be1fcd7b6dfb7caaab63cea66557ee18f332e the remote build fails again with unhelpful message 
`> There were failing tests. See the report at: file:///home/travis/build/engagingspaces/vertx-graphql-service-discovery/graphql-service-publisher/build/reports/tests/test/index.html`

It appears to fail randomly. Restarting the build will sometimes yield success, or it fails with above message.
